<a href="https://colab.research.google.com/github/SaiDhanyaa/ExcelR_Assignments/blob/main/BOOK_RECOMMENDATION_SYSTEM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Build a recommender system by using cosine simillarties score.**

In [266]:
import pandas as pd
import numpy as np

In [267]:
book_df=pd.read_csv("/content/book.csv",encoding='latin-1')
book_df

      Unnamed: 0  ...  Book.Rating
0              1  ...            5
1              2  ...            3
2              3  ...            6
3              4  ...            8
4              5  ...            6
...          ...  ...          ...
9995        9996  ...            7
9996        9997  ...            9
9997        9998  ...            7
9998        9999  ...            8
9999       10000  ...            6

[10000 rows x 4 columns]

In [268]:
book_df

      Unnamed: 0  ...  Book.Rating
0              1  ...            5
1              2  ...            3
2              3  ...            6
3              4  ...            8
4              5  ...            6
...          ...  ...          ...
9995        9996  ...            7
9996        9997  ...            9
9997        9998  ...            7
9998        9999  ...            8
9999       10000  ...            6

[10000 rows x 4 columns]

In [269]:
book_df1=book_df.drop(['Unnamed: 0'], axis=1).rename(columns={"User.ID": "User_ID", "Book.Title": "Book_Title","Book.Rating": "Book_Rating" })

In [270]:
book_df1

      User_ID                                         Book_Title  Book_Rating
0      276726                                Classical Mythology            5
1      276729                                       Clara Callan            3
2      276729                               Decision in Normandy            6
3      276736  Flu: The Story of the Great Influenza Pandemic...            8
4      276737                             The Mummies of Urumchi            6
...       ...                                                ...          ...
9995   162121       American Fried: Adventures of a Happy Eater.            7
9996   162121                              Cannibal In Manhattan            9
9997   162121                    How to Flirt: A Practical Guide            7
9998   162121                                           Twilight            8
9999   162129                       Kids Say the Darndest Things            6

[10000 rows x 3 columns]

In [271]:
# # Preprocessing

In [272]:
#number of unique users in the dataset
User_ID_unique=book_df1.User_ID.unique()

In [273]:
User_ID_unique=pd.DataFrame(User_ID_unique)

In [274]:

####no of unique books in the datasets
len(book_df1.Book_Title.unique())

9659

In [275]:
#### covert long table to wide table
user_book_df = book_df1.pivot_table(index='User_ID',
                                 columns='Book_Title',
                                 values='Book_Rating')

In [276]:
user_book_df

Book_Title   Jason, Madison &amp  ...  Ãƒ?Ã‚?bermorgen.
User_ID                           ...
8                            NaN  ...             NaN
9                            NaN  ...             NaN
10                           NaN  ...             NaN
12                           NaN  ...             NaN
14                           NaN  ...             NaN
...                          ...  ...             ...
278846                       NaN  ...             NaN
278849                       NaN  ...             NaN
278851                       NaN  ...             NaN
278852                       NaN  ...             NaN
278854                       NaN  ...             NaN

[2182 rows x 9659 columns]

In [277]:
# # Build the Model

In [278]:
user_book_df.index = book_df1.User_ID.unique()

In [279]:
user_book_df

Book_Title   Jason, Madison &amp  ...  Ãƒ?Ã‚?bermorgen.
276726                       NaN  ...             NaN
276729                       NaN  ...             NaN
276736                       NaN  ...             NaN
276737                       NaN  ...             NaN
276744                       NaN  ...             NaN
...                          ...  ...             ...
162107                       NaN  ...             NaN
162109                       NaN  ...             NaN
162113                       NaN  ...             NaN
162121                       NaN  ...             NaN
162129                       NaN  ...             NaN

[2182 rows x 9659 columns]

In [280]:
#Impute those NaNs with 0 values
user_book_df.fillna(0, inplace=True)

In [281]:
user_book_df

Book_Title   Jason, Madison &amp  ...  Ãƒ?Ã‚?bermorgen.
276726                       0.0  ...             0.0
276729                       0.0  ...             0.0
276736                       0.0  ...             0.0
276737                       0.0  ...             0.0
276744                       0.0  ...             0.0
...                          ...  ...             ...
162107                       0.0  ...             0.0
162109                       0.0  ...             0.0
162113                       0.0  ...             0.0
162121                       0.0  ...             0.0
162129                       0.0  ...             0.0

[2182 rows x 9659 columns]

In [282]:
#Calculating Cosine Similarity between Users
from sklearn.metrics import pairwise_distances
from scipy.spatial.distance import cosine, correlation

In [283]:
user_sim = 1-pairwise_distances(user_book_df.values,metric='cosine')

In [284]:
user_sim

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [285]:
#Store the results in a dataframe
user_sim_df = pd.DataFrame(user_sim)

In [286]:
#Set the index and column names to user ids 
user_sim_df.index = book_df1.User_ID.unique()
user_sim_df.columns = book_df1.User_ID.unique()

In [287]:
user_sim_df.iloc[0:5, 0:5]

        276726  276729  276736  276737  276744
276726     1.0     0.0     0.0     0.0     0.0
276729     0.0     1.0     0.0     0.0     0.0
276736     0.0     0.0     1.0     0.0     0.0
276737     0.0     0.0     0.0     1.0     0.0
276744     0.0     0.0     0.0     0.0     1.0

In [288]:
np.fill_diagonal(user_sim, 0)
user_sim_df.iloc[0:5, 0:5]

        276726  276729  276736  276737  276744
276726     0.0     0.0     0.0     0.0     0.0
276729     0.0     0.0     0.0     0.0     0.0
276736     0.0     0.0     0.0     0.0     0.0
276737     0.0     0.0     0.0     0.0     0.0
276744     0.0     0.0     0.0     0.0     0.0

In [289]:
#Most Similar Users
user_sim_df.idxmax(axis=1)

276726    276726
276729    276726
276736    276726
276737    276726
276744    276726
           ...
162107    276726
162109    276726
162113    161453
162121    276726
162129    276726
Length: 2182, dtype: int64

In [290]:
book_df1[(book_df1['User_ID']==276729) | (book_df1['User_ID']==276726)]

   User_ID            Book_Title  Book_Rating
0   276726   Classical Mythology            5
1   276729          Clara Callan            3
2   276729  Decision in Normandy            6

In [291]:
user_1=book_df1[book_df1['User_ID']==276729]

In [292]:
user_2=book_df1[book_df1['User_ID']==276726]

In [293]:
user_2.Book_Title

0    Classical Mythology
Name: Book_Title, dtype: object

In [294]:
user_1.Book_Title

1            Clara Callan
2    Decision in Normandy
Name: Book_Title, dtype: object

In [295]:
pd.merge(user_1,user_2,on='Book_Title',how='outer')

   User_ID_x            Book_Title  Book_Rating_x  User_ID_y  Book_Rating_y
0   276729.0          Clara Callan            3.0        NaN            NaN
1   276729.0  Decision in Normandy            6.0        NaN            NaN
2        NaN   Classical Mythology            NaN   276726.0            5.0

# ***since 276729.0	 have read the Clara Callan book and Decision in Normandy	, we cannot recommend Clara Callan book to userid 276726.0 because of the low ratings but we can recommend Decision in Normandy for the userid 276726.0***

# ***we can recommend 	Decision in Normandy book to 276726.0	because of the high ratings. we can recommend Classical Mythology to userid 276729.0 because of the high rating.***